# Generated by Django 5.2.4 on 2025-08-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_headline_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.CharField(default='images/avatar.png', max_length=255),
        ),
    ]
