# Generated by Django 5.2.4 on 2025-08-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='issuing_organization',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
