# Generated by Django 5.2.4 on 2025-09-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_github_url_profile_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.CharField(default='images/avatar1.jpg', max_length=255),
        ),
    ]
