# Generated by Django 5.2.4 on 2026-02-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='num_certifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_educations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_experiences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_skills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
