# Generated by Django 5.2.4 on 2026-02-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_bio_remove_profile_github_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='resume',
            new_name='resume_pdf',
        ),
    ]
