# Generated by Django 5.2.4 on 2026-03-11 10:51

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='num_projects',
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
    ]
