# Generated by Django 5.2.4 on 2026-03-11 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_profile_num_projects_profile_resume_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('technologies_used', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
