# Generated by Django 5.2.4 on 2026-03-11 03:41

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_alter_resumeanalysis_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
